### ISSUE TITLE
Week 9

### ISSUE THREAD

**Issue by CTOverton** [CTOverton/Agent-TAG#16]
- [x] Refine your group agent, based on the discussions that we had during class.  Submit an updated agent 

- [x] Everyone will need to do task 2, which will be the work on the literature review for your paper.  Each person in the group should choose one of the following pieces to work on.  
> Note that one person should choose task a, one person should choose task b, and the remaining ones should do task c.

- [x] a) #13 Find a description of the history/rules of the game of Gin that can be cited.  In your own words, write a description of the history and rules that is no longer than one page long.  (See the paper on Dudo as an example).

- [x] b) #14 Write a summary of MCCFR algorithm in your own words that is no longer than one page long.

- [x] c) #15 Find two articles that relate to the research question you plan to address, other than the ones we have discussed in class. For each article, write a one paragraph summary of the key points of the paper and one paragraph that explains how you are extending this previous work in your research.  Note that in a group with four people, two people will do this task (for a total of 4 papers), and in a group with five people, three people should do this task.

**Comment by CTOverton** [comment]
submitted
